### ISSUE TITLE
Still crashing after completion

### ISSUE THREAD

**Issue by TakumiFujiwara3** [vars1ty/CrossoutLD12#1]
Tried it but im still randomly freezing any ideas why? thx

**Comment by vars1ty** [comment]
Sounds like you aren't using it in the correct way. Can you record a video and upload it here?

**Comment by TakumiFujiwara3** [comment]
its fixed I just had to run it through bottles, steamdeck was just having abit of a moment haha

**Comment by NextRank** [comment]
It shouldn't make a difference if run with a steam install since this is a file patcher right?
